name: suntime
description: Simple sunrise and sunset time calculation for a given location.
version: 0.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  date_utils: ^0.2.0
  timezone: ^0.8.0
